### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by duro** [skevy/react-document-meta#1]
I'm very curious to know how this project is coming along. This is one area that I have been sorely trying to figure out.

**Comment by xpepermint** [comment]
+1

**Comment by itoldya** [comment]
+1

**Comment by jaraquistain** [comment]
+1

**Comment by agilgur5** [comment]
Check out https://github.com/geekyme/react-doc-meta, seems to be production ready but haven't tried it yet

**Comment by catamphetamine** [comment]
I'm dropping this project because it doesn't work with the new builds of React (betas, RCs)

```
"peerDependencies": {
    "react": ">=0.11.0",
    "lodash": ">=3.0.0"
  },
```

**Comment by catamphetamine** [comment]
FYI
https://github.com/kodyl/react-document-meta

**Comment by agilgur5** [comment]
Thought I might recommend https://github.com/nfl/react-helmet. Other than the awesome name (it does the entire head element), it seems to be more or less actively worked on

**Comment by skevy** [comment]
See updated README. Use react-helmet! :)
